In [46]:
import pandas as pd
import numpy as np
import matplotlib
import sklearn

In [47]:
weather = pd.read_csv("../data/thessaloniki_weather_raw.csv")

In [48]:
weather

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,PRCP,PRCP_ATTRIBUTES,SNWD,SNWD_ATTRIBUTES,TAVG,TAVG_ATTRIBUTES,TMAX,TMAX_ATTRIBUTES,TMIN,TMIN_ATTRIBUTES
0,GRM00016622,"MAKEDONIA, GR",40.52,22.971,6.7,1964-01-03,NaN,NaN,NaN,NaN,1.9,"H,,S",3.9,",,S",1.1,",,S"
1,GRM00016622,"MAKEDONIA, GR",40.52,22.971,6.7,1964-01-06,NaN,NaN,NaN,NaN,-0.2,"H,,S",6.1,",,S",-2.8,",,S"
2,GRM00016622,"MAKEDONIA, GR",40.52,22.971,6.7,1964-01-08,NaN,NaN,NaN,NaN,0.8,"H,,S",7.8,",,S",-5.0,",,S"
3,GRM00016622,"MAKEDONIA, GR",40.52,22.971,6.7,1964-01-09,NaN,NaN,NaN,NaN,2.4,"H,,S",7.2,",,S",-1.1,",,S"
4,GRM00016622,"MAKEDONIA, GR",40.52,22.971,6.7,1964-01-13,NaN,NaN,NaN,NaN,-1.2,"H,,S",10.0,",,S",-5.0,",,S"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21206,GRM00016622,"MAKEDONIA, GR",40.52,22.971,6.7,2025-08-20,0.0,",,S",NaN,NaN,25.3,"H,,S",30.4,",,S",NaN,NaN
21207,GRM00016622,"MAKEDONIA, GR",40.52,22.971,6.7,2025-08-21,0.0,",,S",NaN,NaN,25.9,"H,,S",NaN,NaN,20.0,",,S"
21208,GRM00016622,"MAKEDONIA, GR",40.52,22.971,6.7,2025-08-22,0.0,",,S",NaN,NaN,26.6,"H,,S",NaN,NaN,NaN,NaN
21209,GRM00016622,"MAKEDONIA, GR",40.52,22.971,6.7,2025-08-23,0.0,",,S",NaN,NaN,28.0,"H,,S",32.0,",,S",NaN,NaN
21210,GRM00016622,"MAKEDONIA, GR",40.52,22.971,6.7,2025-08-24,NaN,NaN,NaN,NaN,26.6,"H,,S",31.0,",,S",NaN,NaN

In [49]:
weather.shape

(21211, 16)

In [50]:
weather.dtypes

STATION                str
NAME                   str
LATITUDE           float64
LONGITUDE          float64
ELEVATION          float64
DATE                   str
PRCP               float64
PRCP_ATTRIBUTES        str
SNWD               float64
SNWD_ATTRIBUTES        str
TAVG               float64
TAVG_ATTRIBUTES        str
TMAX               float64
TMAX_ATTRIBUTES        str
TMIN               float64
TMIN_ATTRIBUTES        str
dtype: object

In [51]:
weather.isna().sum()

STATION                0
NAME                   0
LATITUDE               0
LONGITUDE              0
ELEVATION              0
DATE                   0
PRCP                5209
PRCP_ATTRIBUTES     5209
SNWD               21145
SNWD_ATTRIBUTES    21145
TAVG                   0
TAVG_ATTRIBUTES        0
TMAX                6894
TMAX_ATTRIBUTES     6894
TMIN                8787
TMIN_ATTRIBUTES     8787
dtype: int64

In [52]:
(weather.isna().mean() * 100).round(1)

STATION             0.0
NAME                0.0
LATITUDE            0.0
LONGITUDE           0.0
ELEVATION           0.0
DATE                0.0
PRCP               24.6
PRCP_ATTRIBUTES    24.6
SNWD               99.7
SNWD_ATTRIBUTES    99.7
TAVG                0.0
TAVG_ATTRIBUTES     0.0
TMAX               32.5
TMAX_ATTRIBUTES    32.5
TMIN               41.4
TMIN_ATTRIBUTES    41.4
dtype: float64

In [53]:
weather.describe()

,LATITUDE,LONGITUDE,ELEVATION,PRCP,SNWD,TAVG,TMAX,TMIN
count,2.121100e+04,2.121100e+04,2.121100e+04,16002.000000,66.000000,21211.000000,14317.000000,12424.000000
mean,4.052000e+01,2.297100e+01,6.700000e+00,1.302393,358.424242,15.396940,20.649843,10.313989
std,7.105595e-15,3.552797e-15,1.776399e-15,5.102234,412.787264,7.831745,8.730691,7.302387
min,4.052000e+01,2.297100e+01,6.700000e+00,0.000000,10.000000,-5.900000,-3.900000,-12.800000
25%,4.052000e+01,2.297100e+01,6.700000e+00,0.000000,20.000000,8.900000,13.200000,4.600000
50%,4.052000e+01,2.297100e+01,6.700000e+00,0.000000,145.000000,15.100000,20.400000,10.600000
75%,4.052000e+01,2.297100e+01,6.700000e+00,0.000000,749.000000,22.300000,28.200000,16.600000
max,4.052000e+01,2.297100e+01,6.700000e+00,154.900000,1199.000000,32.900000,44.000000,27.000000

In [54]:
weather["DATE"].duplicated().sum()

np.int64(0)

In [55]:
weather["DATE"] = pd.to_datetime(weather["DATE"])

In [56]:
weather["DATE"].dt.year.value_counts().sort_index()

DATE
1964    274
1965    359
1966    212
1967    348
1968    366
1969    365
1970    364
1971     90
1973    365
1974    350
1975    364
1976    366
1977    365
1978    365
1979    365
1980    366
1981    365
1982    365
1983    365
1984    366
1985    365
1986    365
1987    365
1988    366
1989    365
1990    365
1991    365
1992    366
1993    365
1994    365
1995    365
1996    366
1997    365
1998    365
1999    364
2000    366
2001    365
2002    365
2003    365
2004    366
2006    365
2007    365
2008    366
2009    365
2010    365
2011    365
2012    366
2013    365
2014    365
2015    365
2016    366
2017    365
2018    365
2019    365
2020    366
2021    362
2022    365
2023    365
2024    355
2025    236
Name: count, dtype: int64

In [57]:
weather["TMAX"].isna().groupby(weather["DATE"].dt.year).sum()

DATE
1964      3
1965      4
1966     10
1967      6
1968     13
1969     79
1970     31
1971      0
1973     42
1974     43
1975     47
1976     42
1977     32
1978     38
1979     48
1980     43
1981     36
1982     93
1983     78
1984     76
1985    114
1986     69
1987    102
1988    106
1989     82
1990    117
1991    110
1992    122
1993    113
1994     98
1995    105
1996    104
1997     71
1998    117
1999    120
2000    205
2001    173
2002    102
2003    135
2004    155
2006    126
2007    131
2008    130
2009    156
2010    176
2011    178
2012    191
2013    295
2014    355
2015    196
2016    194
2017    218
2018    217
2019    179
2020    186
2021    186
2022    204
2023    177
2024    189
2025    126
Name: TMAX, dtype: int64